const colors = {
  light: {
    text: '#0A0E1A',
    tint: '#00B894',
    background: '#F0F5FF',
    foreground: '#0A0E1A',
    card: '#FFFFFF',
    cardForeground: '#0A0E1A',
    primary: '#00B894',
    primaryForeground: '#FFFFFF',
    secondary: '#FF6B35',
    secondaryForeground: '#FFFFFF',
    muted: '#EDF2FF',
    mutedForeground: '#6B7B94',
    accent: '#FFB800',
    accentForeground: '#0A0E1A',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#D8E3F5',
    input: '#D8E3F5',
  },
  dark: {
    text: '#E8F0FF',
    tint: '#00D4AA',
    background: '#0A0E1A',
    foreground: '#E8F0FF',
    card: '#131929',
    cardForeground: '#E8F0FF',
    primary: '#00D4AA',
    primaryForeground: '#0A0E1A',
    secondary: '#FF6B35',
    secondaryForeground: '#FFFFFF',
    muted: '#1A2540',
    mutedForeground: '#8B9BBE',
    accent: '#FFB800',
    accentForeground: '#0A0E1A',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#1E2D45',
    input: '#1E2D45',
  },
  radius: 16,
};

export default colors;
