const colors = {
  light: {
    text: '#1A0E2E',
    tint: '#00BFA5',
    background: '#FAF7FF',
    foreground: '#1A0E2E',
    card: '#FFFFFF',
    cardForeground: '#1A0E2E',
    primary: '#00C4A7',
    primaryForeground: '#FFFFFF',
    secondary: '#FF6FA3',
    secondaryForeground: '#FFFFFF',
    muted: '#F0EAFF',
    mutedForeground: '#7B6EA0',
    accent: '#FFB347',
    accentForeground: '#1A0E2E',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E4D9F5',
    input: '#E4D9F5',
  },
  dark: {
    text: '#EDE7FF',
    tint: '#00D4AA',
    background: '#0E0A1C',
    foreground: '#EDE7FF',
    card: '#1A1430',
    cardForeground: '#EDE7FF',
    primary: '#00D4AA',
    primaryForeground: '#0E0A1C',
    secondary: '#FF7EB3',
    secondaryForeground: '#FFFFFF',
    muted: '#231740',
    mutedForeground: '#9D8EC0',
    accent: '#FFB347',
    accentForeground: '#0E0A1C',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#2E1E50',
    input: '#2E1E50',
  },
  radius: 20,
};

export default colors;
