const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.YOKI_QA_PLAYWRIGHT || 'playwright');
const root = path.resolve(process.env.YOKI_QA_EXPORT || path.join(__dirname, '../../../build-yoki-v2-life'));
const mime = {'.html':'text/html','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg','.ttf':'font/ttf','.mp3':'audio/mpeg'};
const server = http.createServer((req,res) => {
  let file = path.join(root, decodeURIComponent(new URL(req.url,'http://localhost').pathname));
  if (!file.startsWith(root)) {res.writeHead(403).end();return;}
  if (!fs.existsSync(file) || fs.statSync(file).isDirectory()) file = path.join(root,'index.html');
  res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream'); fs.createReadStream(file).pipe(res);
});
(async()=>{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  const browser = await chromium.launch({executablePath:process.env.YOKI_QA_BROWSER,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
  try {
    const page=await browser.newPage({viewport:{width:390,height:844}});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.addInitScript(()=>{
      if(localStorage.getItem('qa-seeded'))return;
      localStorage.setItem('@mentore/profile_v1',JSON.stringify({nickname:'テスト',ageRange:'回答しない',gender:'回答しない'}));
      localStorage.setItem('@mentore/mascot_name_v1','よっきー');
      localStorage.setItem('@mentore/feed_state_v1',JSON.stringify({points:100,lastFeedTime:null,satietyAtFeed:50}));
      localStorage.setItem('@mentore/encounters_v1',JSON.stringify({list:[{charKey:'egg',metDate:'2026-09-01'}]}));
      localStorage.setItem('qa-seeded','true');
    });
    await page.goto('http://127.0.0.1:'+server.address().port);
    const resident=page.getByTestId('room-resident');
    await resident.waitFor({state:'visible',timeout:30000});
    await page.waitForTimeout(3000);
    const pose=async text=>page.waitForFunction(t=>document.querySelector('[data-testid="room-resident"]')?.getAttribute('aria-label')?.includes(t),text,{timeout:18000}).catch(async e=>{console.log(await resident.evaluate(el=>el.outerHTML.slice(0,1400)));console.log(errors);throw e;});
    await page.getByTestId('room-bed').click();
    await pose('ひと休みしています');
    console.log('PASS bed request reaches rest pose');
    await page.getByTestId('home-more-menu').click();
    const paused=await resident.getAttribute('style');
    await page.waitForTimeout(1500);
    assert.equal(await resident.getAttribute('style'),paused);
    await page.getByLabel('閉じる',{exact:true}).last().click();
    await page.getByTestId('room-meal').click();
    await page.getByText('きのみ',{exact:true}).click();
    await pose('おやつの時間');
    const feeding=await page.evaluate(()=>JSON.parse(localStorage.getItem('@mentore/feed_state_v1')));
    assert.equal(feeding.points,95);
    console.log('PASS bed-to-meal route, single payment and eating pose');
    const box=await resident.boundingBox();
    await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
    await page.mouse.down();await page.waitForTimeout(450);
    assert.equal(await resident.evaluate(el=>el.style.zIndex),'999');
    await page.mouse.move(box.x+box.width/2+20,box.y+box.height/2-50,{steps:5});
    await page.mouse.up();await page.waitForTimeout(600);
    assert.notEqual(await resident.evaluate(el=>el.style.zIndex),'999');
    console.log('PASS lift and release during routine');
    await page.getByTestId('home-more-menu').click();
    await page.waitForTimeout(200);
    const stopped=await resident.getAttribute('style');
    await page.waitForTimeout(7000);
    assert.equal(await resident.getAttribute('style'),stopped);
    console.log('PASS interrupted routine stays stopped behind sheet');
    await page.getByLabel('閉じる',{exact:true}).last().click();
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.waitForTimeout(300);
    const beforeRest=await resident.getAttribute('style');
    await page.getByTestId('room-bed').click();
    await pose('ひと休みしています');
    const still=await resident.getAttribute('style');
    assert.equal(still,beforeRest);
    await page.waitForTimeout(1000);
    assert.equal(await resident.getAttribute('style'),still);
    assert.deepEqual(errors,[]);
    console.log('PASS reduced-motion rest; no page errors');
    await page.getByTestId('room-record').click();
    await page.getByTestId('quick-mood-2').click();
    await page.getByTestId('quick-record-save').click();
    await page.getByTestId('light-flow-feedback').waitFor({state:'visible'});
    assert.equal(await page.getByTestId('light-flow-particle').count(),0);
    const energyKey=await page.evaluate(()=>Object.keys(localStorage).find(k=>k.includes('light_energy')));
    assert.ok(energyKey);
    const energy=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),energyKey);
    assert.equal(energy.flags.mood,true);
    await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
    await page.getByTestId('light-flow-feedback').waitFor({state:'hidden'});
    await page.waitForTimeout(5000);
    await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});
    await page.getByTestId('light-flow-feedback').waitFor({state:'visible'});
    await page.getByTestId('light-flow-garden').click();
    await page.getByTestId('energy-garden').waitFor({state:'visible'});
    console.log('PASS saved record feedback, static mode, hidden-tab pause, garden link');
    await page.getByText('部屋',{exact:true}).last().click();
    await page.getByTestId('room-record').click();
    await page.getByTestId('quick-mood-4').click();
    await page.getByTestId('quick-record-save').click();
    await page.waitForTimeout(1000);
    assert.equal(await page.getByTestId('light-flow-feedback').count(),0);
    const energyAfter=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),energyKey);
    assert.equal(energyAfter.flags.mood,true);
    assert.ok(energyAfter.totalEnergy-energy.totalEnergy<0.1);
    assert.deepEqual(errors,[]);
    console.log('PASS same-day update has no duplicate energy celebration; no page errors');
    const beforeGames=await page.evaluate(()=>({feed:localStorage.getItem('@mentore/feed_state_v1'),game:localStorage.getItem('@mentore/mini_game_v1')}));
    await page.getByTestId('room-music').click();
    await page.getByText('グリッティ・ブギ',{exact:true}).click();
    await page.getByText('つぎへ',{exact:true}).click();
    for(const mode of ['TAP BEAT','RHYTHM JUMP','RHYTHM SWIPE','RHYTHM COPY','RHYTHM RELAX']){
      await page.getByText(mode,{exact:true}).click();
      await page.getByText('つぎへ',{exact:true}).click();
      await page.getByText('START',{exact:true}).click();
      await page.waitForTimeout(1200);
      await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
      await page.getByText('演奏を中断しました。もう一度はじめられます。',{exact:true}).waitFor();
      await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});
      await page.waitForTimeout(200);
      assert.deepEqual(await page.evaluate(()=>({feed:localStorage.getItem('@mentore/feed_state_v1'),game:localStorage.getItem('@mentore/mini_game_v1')})),beforeGames);
      await page.getByText('もどる',{exact:true}).click();
      console.log(`PASS ${mode}: hidden-tab interruption returns to selection without rewards`);
    }
    assert.deepEqual(errors,[]);
    const first=await browser.newPage({viewport:{width:320,height:568}});
    first.on('pageerror',e=>errors.push(e.message));
    await first.goto('http://127.0.0.1:'+server.address().port);
    await first.getByPlaceholder('例: ゆき').fill('はじめて');
    await first.getByText('回答しない',{exact:true}).nth(0).click();
    await first.getByText('回答しない',{exact:true}).nth(1).click();
    await first.getByText('いっしょにはじめる',{exact:true}).click();
    await first.getByTestId('room-scene').waitFor({state:'visible'});
    await first.waitForTimeout(700);
    const greeting=first.getByText('よろしくね！',{exact:true});
    if(await greeting.isVisible()) await greeting.click();
    await first.getByTestId('room-record').click();
    await first.getByTestId('quick-mood-3').click();
    await first.waitForTimeout(500);
    const saveBox=await first.getByTestId('quick-record-save').boundingBox();
    assert.ok(saveBox.y>=0 && saveBox.y+saveBox.height<=568);
    await first.getByTestId('quick-record-save').click();
    await first.getByTestId('light-flow-feedback').waitFor({state:'visible'});
    await first.reload();
    await first.getByTestId('room-scene').waitFor({state:'visible'});
    await first.waitForTimeout(3000);
    assert.equal(await first.getByTestId('light-flow-feedback').count(),0);
    console.log('PASS first-run guest onboarding reaches room at 320x568');
    console.log('PASS compact basic-record save and reload without replaying energy feedback');
    assert.deepEqual(errors,[]);
  } finally {await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
