import React, { useEffect, useState } from 'react';
import { Alert, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Item, ItemCategory, useItems } from '@/contexts/ItemContext';
import { StageCharacter } from '@/components/StageCharacter';

const blank = (): Partial<Item> => ({ name:'', category:'accessory', cost:0, assetUrl:'', posX:0, posY:0, scale:1, isActive:true });
export default function AdminScreen() {
 const router=useRouter(); const {adminItems,saveItem,disableItem,refreshAdminItems,error}=useItems(); const [form,setForm]=useState<Partial<Item>>(blank()); const [saving,setSaving]=useState(false); const [adminError,setAdminError]=useState('');
 useEffect(()=>{refreshAdminItems().catch(e=>setAdminError(e instanceof Error?e.message:'管理者権限を確認してください'));},[refreshAdminItems]);
 const set=(key:keyof Item,value:any)=>setForm(f=>({...f,[key]:value}));
 const submit=async()=>{ if(!form.name || !form.assetUrl){Alert.alert('名前とアセットURLを入力してください');return;} setSaving(true);try{await saveItem({...form,cost:Number(form.cost)||0,posX:Number(form.posX)||0,posY:Number(form.posY)||0,scale:Number(form.scale)||1});setForm(blank());}catch(e){Alert.alert('保存できませんでした',e instanceof Error?e.message:'管理者権限を確認してください');}finally{setSaving(false);}};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.wrap}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ 戻る</Text></Pressable><Text style={s.title}>アイテム管理</Text></View>
 <Text style={s.help}>この画面の操作はサーバー側で管理者権限を確認します。画像は公開URLを入力してください。</Text>{(adminError||error)&&<Text style={s.error}>{adminError||error}</Text>}
 <View style={s.form}><Text style={s.section}>{form.id?'アイテムを編集':'新しいアイテム'}</Text>
 <TextInput value={form.name||''} onChangeText={v=>set('name',v)} placeholder="名前" style={s.input}/><TextInput value={form.assetUrl||''} onChangeText={v=>set('assetUrl',v)} placeholder="画像 / 音声 URL" autoCapitalize="none" style={s.input}/>
 <View style={s.categories}>{(['food','accessory','background','voice'] as ItemCategory[]).map(c=><Pressable key={c} onPress={()=>set('category',c)} style={[s.chip,form.category===c&&s.chipOn]}><Text style={form.category===c?s.chipTextOn:s.chipText}>{c}</Text></Pressable>)}</View>
 <TextInput value={String(form.cost??0)} onChangeText={v=>set('cost',v)} keyboardType="numeric" placeholder="コスト" style={s.input}/>
 {form.category==='accessory'&&<><Text style={s.label}>重ね位置とサイズ（ライブプレビュー）</Text><View style={s.preview}><StageCharacter stage="egg" mood="normal" size={115} growthSize={1}/>{form.assetUrl?<View pointerEvents="none" style={StyleSheet.absoluteFillObject}><Image source={{uri:form.assetUrl}} style={{position:'absolute',width:115*(Number(form.scale)||1),height:115*(Number(form.scale)||1),left:50+(Number(form.posX)||0),top:38+(Number(form.posY)||0),resizeMode:'contain'}}/></View>:null}</View><View style={s.row}>{(['posX','posY','scale'] as const).map(k=><TextInput key={k} value={String(form[k]??(k==='scale'?1:0))} onChangeText={v=>set(k,v)} keyboardType="numeric" placeholder={k} style={[s.input,s.small]}/>)}</View></>}
 <View style={s.active}><Text>公開中</Text><Switch value={!!form.isActive} onValueChange={v=>set('isActive',v)}/></View><Pressable onPress={submit} style={s.save}><Text style={s.saveText}>{saving?'保存中…':'保存する'}</Text></Pressable></View>
 <Text style={s.section}>登録済みアイテム</Text>{adminItems.map(item=><View style={s.item} key={item.id}><Image source={{uri:item.assetUrl}} style={s.thumb}/><View style={{flex:1}}><Text style={s.itemName}>{item.name}</Text><Text style={s.meta}>{item.category} · {item.cost} pt · {item.isActive?'公開中':'非公開'}</Text></View><Switch value={item.isActive} onValueChange={isActive=>saveItem({...item,isActive}).catch(e=>Alert.alert('操作できません',e.message))}/><Pressable onPress={()=>setForm(item)}><Text style={s.edit}>編集</Text></Pressable>{item.isActive?<Pressable onPress={()=>Alert.alert('非公開にしますか？','購入済みのユーザーのデータは保持されます。',[{text:'キャンセル'},{text:'非公開',style:'destructive',onPress:()=>disableItem(item.id).catch(e=>Alert.alert('操作できません',e.message))}])}><Text style={s.remove}>非公開</Text></Pressable>:null}</View>)}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F5F4FF'},wrap:{padding:20,gap:12},header:{flexDirection:'row',alignItems:'center',gap:20},back:{fontSize:16,color:'#5B57A8'},title:{fontSize:21,fontWeight:'800',color:'#332F68'},help:{fontSize:12,color:'#68647C',lineHeight:18},error:{color:'#B22'},form:{backgroundColor:'white',padding:15,borderRadius:16,gap:10},section:{fontSize:16,fontWeight:'800',color:'#373252'},input:{borderWidth:1,borderColor:'#DDD9F0',borderRadius:9,padding:10,fontSize:14,backgroundColor:'#FFF'},categories:{flexDirection:'row',flexWrap:'wrap',gap:6},chip:{paddingHorizontal:9,paddingVertical:7,backgroundColor:'#ECEAF5',borderRadius:99},chipOn:{backgroundColor:'#6258B6'},chipText:{fontSize:12,color:'#555'},chipTextOn:{fontSize:12,color:'white',fontWeight:'700'},label:{fontSize:13,fontWeight:'700'},preview:{height:185,backgroundColor:'#EEF0FF',borderRadius:12,alignItems:'center',justifyContent:'center',overflow:'hidden'},row:{flexDirection:'row',gap:8},small:{flex:1},active:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},save:{backgroundColor:'#554AA2',padding:12,borderRadius:10},saveText:{color:'white',fontWeight:'800',textAlign:'center'},item:{backgroundColor:'white',borderRadius:12,padding:10,flexDirection:'row',alignItems:'center',gap:8},thumb:{width:42,height:42,borderRadius:7,backgroundColor:'#EEE',resizeMode:'contain'},itemName:{fontWeight:'700'},meta:{fontSize:11,color:'#777',marginTop:3},edit:{color:'#554AA2',fontWeight:'700',fontSize:12},remove:{color:'#B33',fontWeight:'700',fontSize:12}});